language: cpp

dist: bionic

notifications:
  email:
    on_success: change
    on_failure: always

env:
  global:
    - SCONS_CACHE=$HOME/.scons_cache
    - SCONS_CACHE_LIMIT=1024
    - OPTIONS="debug_symbols=yes verbose=no progress=yes builtin_libpng=yes"
    - GODOT_REPO_URL="https://github.com/godotengine/godot"
    - GODOT_DIR="$HOME/godot/"
    - GODOT_BINARY_DIR="$HOME/godot/bin/"

cache:
  directories:
    - $SCONS_CACHE

matrix:
  include:
    - name: Linux headless (debug, GCC 9, with editor)
      stage: build
      env: PLATFORM=server TOOLS=yes TARGET=debug CACHE_NAME=${PLATFORM}-tools-gcc-9 MATRIX_EVAL="CC=gcc-9 && CXX=g++-9" EXTRA_ARGS="warnings=extra werror=yes" GODOT_BINARY="godot_server.x11.tools.64"
      os: linux
      compiler: gcc-9
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - &gcc9_deps [gcc-9, g++-9]
            - &linux_deps [libasound2-dev, libgl1-mesa-dev, libglu1-mesa-dev, libx11-dev, libxcursor-dev, libxi-dev, libxinerama-dev, libxrandr-dev]
            
    - name: Linux headless (release_debug, GCC 9, no editor)
      stage: build
      env: PLATFORM=server TOOLS=no TARGET=release_debug CACHE_NAME=${PLATFORM}-gcc-9 MATRIX_EVAL="CC=gcc-9 && CXX=g++-9" EXTRA_ARGS="warnings=extra werror=yes" GODOT_BINARY="godot_server.x11.opt.debug.64"
      os: linux
      compiler: gcc-9
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - &gcc9_deps [gcc-9, g++-9]
            - &linux_deps [libasound2-dev, libgl1-mesa-dev, libglu1-mesa-dev, libx11-dev, libxcursor-dev, libxi-dev, libxinerama-dev, libxrandr-dev]

    - name: Linux headless (release, clang)
      stage: build
      env: PLATFORM=server TOOLS=no TARGET=release CACHE_NAME=${PLATFORM}-clang EXTRA_ARGS="warnings=extra werror=no" GODOT_BINARY="godot_server.x11.opt.64.llvm"
      os: linux
      compiler: clang
      addons:
        apt:
          packages:
            - &linux_deps [libasound2-dev, libgl1-mesa-dev, libglu1-mesa-dev, libx11-dev, libxcursor-dev, libxi-dev, libxinerama-dev, libxrandr-dev]

before_install:
  - eval "${MATRIX_EVAL}"

install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      pyenv global 3.8 system;
      pip3 install --user scons;
    fi

before_script:
  - cd "$HOME"
  - git clone --depth=1 "$GODOT_REPO_URL" && cd "$GODOT_DIR"

script:
  - scons -j2 CC=$CC CXX=$CXX platform=$PLATFORM tools=$TOOLS target=$TARGET $OPTIONS $EXTRA_ARGS &&
    if [ "$TARGET" != "release" ]; then
      if [ "$PLATFORM" = "server" ]; then
        $TRAVIS_BUILD_DIR/test.sh "$GODOT_BINARY_DIR""$GODOT_BINARY";
      else
        $TRAVIS_BUILD_DIR/test.sh "$GODOT_BINARY_DIR""$GODOT_BINARY" --no-window;
      fi
    fi
